### ISSUE TITLE
Readme.md - Init Project uses ebay and eBay

### ISSUE THREAD

**Issue by simonfrancis** [eBay/nvidiagpubeat#5]
The commands in the Init Project section of Readme.md use a mix of ebay and eBay. I think these lines:
> mkdir $WORKSPACE/src/github.com/eBay
> cd $WORKSPACE/src/github.com/eBay

need to be lower case ('ebay') for the go import statements to work? Or since the GitHub repository is 'eBay' you might want to standardise on using 'eBay' everywhere instead?

**Comment by deepujain** [comment]
@simonfrancis Thanks for bringing it up. I did notice this confusion, eBay repository has an upper case 'B' as you noticed. I tried two options 
1. Clone the repository with `eBay` and then rename the repository to ebay as the entire golang code uses lower case ebay. This resulted in successful compilation. Updated README.md accordingly.
2.  Clone the repository with `eBay` and i modified the entire nvidiagpubeat to use eBay instead of ebay. Golang did not like to and it resulted in compilation errors. 

I stuck with option 1. 
However, i noticed, below option to work.
3. Clone as 'eBay' and leave nvidiagpubeat to use ebay. On Mac, i see that `case` did not make any difference, hence i removed the changes to README.md .

```
$ pwd
/Users/dvasthimal/Documents/ebay/opensource/beats_dev/src/github.com
LM-SJL-11004865:github.com dvasthimal$ ls -l
total 0
drwxr-xr-x  3 dvasthimal  110133969  96 Jan 19 23:43 eBay
drwxr-xr-x  3 dvasthimal  110133969  96 Jan 19 23:42 elastic
LM-SJL-11004865:github.com dvasthimal$ cd ebay
LM-SJL-11004865:ebay dvasthimal$ pwd
/Users/dvasthimal/Documents/ebay/opensource/beats_dev/src/github.com/ebay
LM-SJL-11004865:ebay dvasthimal$ ls -l
total 0
drwxr-xr-x  20 dvasthimal  110133969  640 Jan 19 23:43 nvidiagpubeat
LM-SJL-11004865:ebay dvasthimal$ cd nvidiagpubeat/
LM-SJL-11004865:nvidiagpubeat dvasthimal$ 
```


Build succeeds for `cd that uses ebay`, if you follow the exact steps mentioned in README.md that uses a mix of eBay and ebay. Here, even though the directory was eBay but using cd with ebay works.

```
cd $WORKSPACE/src/github.com/ebay/nvidiagpubeat/
make setup
make
```
But, it fails for `cd that uses eBay`
```
cd $WORKSPACE/src/github.com/eBay/nvidiagpubeat/
make setup
make
```

**Comment by deepujain** [comment]
But your correct. If one is using auto-complete then `cd would end up using eBay` instead of `ebay` and build step would `fail`.

**Comment by somabc** [comment]
On a case sensitive file system (linux) you have to use lower case "ebay" for the build scripts to complete.

**Comment by deepujain** [comment]
@simonfrancis @somabc Thanks for using nvidiagpubeat.

ReadMe is updated and consistently uses `ebay` so that it works well in case-sensitive file systems, like Linux.

Please update this Issue with results of your test.
